version: "3"
services:
  drachenlord:
    build: .
    environment:
      DISCORD_API_TOKEN: <ODQyMjg1MTYxMDQ3NjU0NDcw.YJzFLw.R6g3C_aZx6WbArLAkWr1gP1AkSM>
      ENABLE_RANDOM_JOINS: "True"
      LOGGING_CHANNEL: <your-logging-textchannel-id-as-integer>
