version: "3"
services:
  drachenlord:
    build: .
    environment:
      DISCORD_API_TOKEN: <ODQyMjg1MTYxMDQ3NjU0NDcw.YJzFLw.nomI8fWddNPlg4Bk6ewVb_2cdHc>
      ENABLE_RANDOM_JOINS: "True"
      LOGGING_CHANNEL: <your-logging-textchannel-id-as-integer>
